Chore: bump outdated num and rustc versions
arrayfire/arrayfire-rust pull request #294
Opened 2021-05-03 15:59 UTC by jkelleyrtp

I ran "cargo-test" and got 

`test src/algorithm/mod.rs - algorithm::max_ragged (line 1489) ... FAILED`

both before and after the version bump, so there aren't any regressions.

max_ragged seems to be failing because "_af_max_ragged" doesn't show up in the macos lib folder for whatever reason.

My IDE also formatted Cargo.toml,  but I can try and undo that if autoformatting is unwanted.

2021-05-03 16:28 UTC, 9prady9 requested changes
Can you please separate the formatting changes into a separate commit preferably before the dependency version updates in history.

We prefer keeping formatting changes from any other kind of code changes.

2021-05-03 16:29 UTC, 9prady9 commented
> max_ragged seems to be failing because "_af_max_ragged" doesn't show up in the macos lib folder for whatever reason.

I haven't had such failures until now, although we had the jobs run in past couple of weeks. So, hard to tell what is causing the this failure on your system. Hopefully, we will know more once the ci jobs run.

2021-05-04 23:28 UTC, jkelleyrtp commented
I just got rid of the formatting changes altogether.  I use the "Better TOML" plugin for auto toml formatting if you feel like setting up formatting on the .toml files.

2021-05-05 06:03 UTC, 9prady9 approved these changes
Thank you.

Sure, I can add a toml formatter to avoid different styles for each addition. I will look into it soon.

2021-05-05 06:11 UTC, merged